FROM plugins/base:arm

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" \
  org.label-schema.name="Drone Codecov" \
  org.label-schema.vendor="Drone.IO Community" \
  org.label-schema.schema-version="1.0"

RUN apk add --no-cache bash git mercurial curl && \
  curl -sLo /bin/codecov https://codecov.io/bash && \
  chmod +x /bin/codecov

ADD release/linux/arm/drone-codecov /bin/
ENTRYPOINT ["/bin/drone-codecov"]
